spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskManager
    username: postgres
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true